### ISSUE TITLE
local integration vs. server integration

### ISSUE THREAD

**Issue by rilke1999** [Flo-R1der/ambientika-smart_4_home-assistant#1]
Thanks for your excellent findings, saves a lot wof work. I was trying enable a more local way to integrate my 3 ambientika smart vents. I started to intercept the traffic between the STM32 and and the esp32 but I need to analyze that further.

**Comment by Flo-R1der** [comment]
Hi rilke1999,
I was also curious if I can integrate my Ambientika device locally. I already had contact with someone from the company and they replied to my questions about a **RoadMap** and **local integration** (German answer):

> Hallo Herr Frei,
> 
> Geplant ist zur Zeit noch eine Wochenzeitschaltuhr und ein Programm zur Smarthomeanbindung. Das kann allerdings noch bis zum Ende des Jahres dauern.
> 
> Das läuft leider nur über den Südwind Server ab.

Which translates to (English):
> Hello Mr. Frei,
> Currently, we are planning a weekly timer and a program for smart home integration.
> However, this may take until the end of the year.
> Unfortunately, this only works via the Südwind server.

So REST can't be used in an official way. Maybe there are some network technicians out there that are willing to do it. But maybe the official “smart home integration” will be the long-term solution - whatever that means in detail.
