### ISSUE TITLE
Picture of the wireless module?

### ISSUE THREAD

**Issue by plaes** [Flo-R1der/ambientika-smart_4_home-assistant#2]
Do you by any chance have a picture of the wireless module?

This is the picture of the PCB of Ambientica Advanced+:
![image](https://github.com/user-attachments/assets/dee4dc50-67db-4d20-a680-193fa8811a39)

From the PCB I can deduce that it uses either RS422 or RS485 as communication between devices (so possibly modbus?)

**Comment by plaes** [comment]
Well no worries, I'm just wondering whether Wireless module is also "connectable" via the RS422/RS485 (the black/blue/red connector + upside down chip labelled 65176B). This might possibly  give better control of the device (read status, etc). 

Also, 6 unpopulated pins just below the msp430 seems to be also routed to the UART pins of the MSP430, but I have yet to power up the device and observe the traffic from there. (I did the bottom/front stackup already in GIMP, but haven't yet had time to trace out the connections...)

**Comment by plaes** [comment]
Managed to do some tracing:
![image](https://github.com/user-attachments/assets/0aa1ef93-3ed0-48af-b594-4c966e952706)

**Comment by plaes** [comment]
Really cool, can you also identify the chip on the right of ESP32?

**Comment by Flo-R1der** [comment]
Sure
![IMG_20241101_143426.jpg](https://github.com/user-attachments/assets/a468dda5-7c36-4d03-aac1-b4557afa7f86)
